# Generated by Django 3.0.6 on 2020-07-11 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2020, 7, 11, 23, 5, 4, 735494))),
                ('article_type', models.CharField(max_length=30)),
                ('article_author', models.CharField(max_length=30)),
                ('main_image', models.ImageField(upload_to='images/')),
                ('main_img_caption', models.TextField()),
                ('second_title', models.TextField()),
                ('second_title_article', models.TextField()),
                ('second_image', models.ImageField(upload_to='images/')),
                ('third_title', models.TextField()),
                ('third_title_article', models.TextField()),
                ('third_image', models.ImageField(upload_to='images/')),
                ('fourth_title', models.TextField()),
                ('fourth_title_article', models.TextField()),
                ('fourth_image', models.ImageField(upload_to='images/')),
                ('article_display', models.BooleanField(default=True)),
                ('article_page_views', models.IntegerField(default=0)),
                ('video_clip', models.FileField(upload_to='video/')),
            ],
        ),
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('public_name', models.CharField(max_length=30)),
                ('account_access', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('instagram_link', models.TextField()),
                ('facebook_link', models.TextField()),
                ('image_upload_permission', models.BooleanField(default=False)),
                ('video_upload_permission', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(default=datetime.datetime(2020, 7, 11, 23, 5, 4, 692427))),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('website_link', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('post_title', models.CharField(max_length=100)),
                ('post_id', models.IntegerField()),
                ('comment_reply', models.TextField()),
                ('comment_date', models.DateTimeField(default=datetime.datetime(2020, 7, 11, 23, 5, 4, 736717))),
            ],
        ),
    ]
