# Generated by Django 3.0.6 on 2020-07-11 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='fourth_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 23, 24, 25, 642771)),
        ),
        migrations.AlterField(
            model_name='articles',
            name='second_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='video_clip',
            field=models.FileField(blank=True, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 23, 24, 25, 621282)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 23, 24, 25, 643870)),
        ),
    ]
