# Generated by Django 3.0.6 on 2020-07-12 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200711_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='url_str',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 1, 6, 31, 83416)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 1, 6, 31, 58889)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 1, 6, 31, 84626)),
        ),
    ]
