# Generated by Django 3.0.6 on 2020-07-12 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200713_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='fourth_title_article',
            new_name='fourth_title_article_para1',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='second_title_article',
            new_name='fourth_title_article_para2',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='third_title_article',
            new_name='fourth_title_article_para3',
        ),
        migrations.AddField(
            model_name='articles',
            name='article_tag1',
            field=models.CharField(default='s', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='article_tag2',
            field=models.CharField(default='s', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='article_tag3',
            field=models.CharField(default='s', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='article_tag4',
            field=models.CharField(default='s', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='second_title_article_para1',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='second_title_article_para2',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='third_title_article_key_point1',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='third_title_article_key_point2',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='third_title_article_key_point3',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='third_title_article_key_point4',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='third_title_article_key_point5',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='third_title_article_para1',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='third_title_article_para2',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='third_title_article_para3',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articles',
            name='third_title_article_para4',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authors',
            name='facebook_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authors',
            name='instagram_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authors',
            name='pintrest_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authors',
            name='twitter_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authors',
            name='website_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authors',
            name='youtube_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 2, 42, 22, 145744)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 2, 42, 22, 120828)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 2, 42, 22, 147230)),
        ),
    ]
