# Generated by Django 3.0.6 on 2020-07-12 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200713_0243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='fourth_title_article_para1',
            new_name='fourth_title_text_para1',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='fourth_title_article_para2',
            new_name='fourth_title_text_para2',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='fourth_title_article_para3',
            new_name='fourth_title_text_para3',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='second_title_article_para1',
            new_name='second_title_text_para1',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='second_title_article_para2',
            new_name='second_title_text_para2',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='third_title_article_key_point1',
            new_name='third_title_text_key_point1',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='third_title_article_key_point2',
            new_name='third_title_text_key_point2',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='third_title_article_key_point3',
            new_name='third_title_text_key_point3',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='third_title_article_key_point4',
            new_name='third_title_text_key_point4',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='third_title_article_key_point5',
            new_name='third_title_text_key_point5',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='third_title_article_para1',
            new_name='third_title_text_para1',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='third_title_article_para2',
            new_name='third_title_text_para2',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='third_title_article_para3',
            new_name='third_title_text_para3',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='third_title_article_para4',
            new_name='third_title_text_para4',
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 2, 45, 58, 795504)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 2, 45, 58, 771066)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 2, 45, 58, 796918)),
        ),
    ]
