# Generated by Django 3.0.6 on 2020-07-13 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200713_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='linkedin_link',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authors',
            name='pintrest_link',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authors',
            name='twitter_link',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authors',
            name='website_link',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authors',
            name='youtube_link',
            field=models.TextField(default='s'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 7, 45, 59, 740981)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 7, 45, 59, 718645)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 7, 45, 59, 742432)),
        ),
    ]
