# Generated by Django 3.0.6 on 2020-07-13 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200713_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='comment_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 10, 44, 17, 690634)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 10, 44, 17, 668916)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 10, 44, 17, 692017)),
        ),
    ]
