# Generated by Django 3.0.6 on 2020-07-13 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200713_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 12, 29, 38, 772731)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 12, 29, 38, 750436)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 12, 29, 38, 774122)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_reply',
            field=models.TextField(blank=True),
        ),
    ]
