# Generated by Django 3.0.6 on 2020-07-13 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200713_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 22, 13, 27, 358273)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 22, 13, 27, 333934)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 22, 13, 27, 359977)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='website_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
