# Generated by Django 3.0.6 on 2020-07-14 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200714_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='youtube_embed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='youtube_video_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articles',
            name='youtube_video_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 15, 24, 43, 781158)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 15, 24, 43, 759734)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 15, 24, 43, 782614)),
        ),
    ]
