# Generated by Django 3.0.6 on 2020-07-14 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200714_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='review_star',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 21, 54, 55, 542538)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 21, 54, 55, 519832)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 21, 54, 55, 544028)),
        ),
    ]
