# Generated by Django 3.0.6 on 2020-07-15 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200714_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='author_url',
            field=models.TextField(default='chatur45'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 16, 2, 9, 511636)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 16, 2, 9, 489691)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 16, 2, 9, 513101)),
        ),
    ]
