# Generated by Django 3.0.6 on 2020-07-15 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200715_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author_url',
            field=models.TextField(default='chatur45'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 17, 36, 2, 221182)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 17, 36, 2, 198346)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 17, 36, 2, 222672)),
        ),
    ]
