# Generated by Django 3.0.6 on 2020-07-15 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200715_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.TextField()),
                ('phone', models.IntegerField()),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('message_date', models.DateTimeField(default=datetime.datetime(2020, 7, 15, 18, 25, 56, 843591))),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 18, 25, 56, 841328)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 18, 25, 56, 819111)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 18, 25, 56, 842862)),
        ),
    ]
