# Generated by Django 3.0.6 on 2020-07-15 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200715_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='myfield',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red')], default='red', max_length=256),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 19, 13, 6, 12161)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 19, 13, 5, 988750)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 19, 13, 6, 13841)),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 19, 13, 6, 14659)),
        ),
    ]
