# Generated by Django 3.0.6 on 2020-07-18 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200716_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_author',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_display',
            field=models.BooleanField(default=True, verbose_name='Show on Website'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_tag1',
            field=models.CharField(max_length=50, verbose_name='Article Tag 1'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_tag2',
            field=models.CharField(max_length=50, verbose_name='Article Tag 2'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_tag3',
            field=models.CharField(max_length=50, verbose_name='Article Tag 3'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_tag4',
            field=models.CharField(max_length=50, verbose_name='Article Tag 4'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_type',
            field=models.CharField(choices=[('Trending News', 'Trending News'), ('Science', 'Science'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Automobile', 'Automobile'), ('Worldwide', 'Worldwide'), ('Reviews', 'Reviews'), ('Health Care', 'Health Care'), ('Gadgets', 'Gadgets'), ('Others', 'Others')], max_length=30, verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='author_url',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='articles',
            name='comment_status',
            field=models.BooleanField(default=True, verbose_name='Allow Comments'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='fourth_image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Fourth Image(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='fourth_title',
            field=models.TextField(blank=True, verbose_name='Title 4(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='fourth_title_text_para1',
            field=models.TextField(blank=True, verbose_name='Title 4 Paragraph 1(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='fourth_title_text_para2',
            field=models.TextField(blank=True, verbose_name='Title 4 Paragraph 2(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='fourth_title_text_para3',
            field=models.TextField(blank=True, verbose_name='Title 4 Paragraph 3(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='main_image',
            field=models.ImageField(upload_to='images/', verbose_name='Top Image'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='main_img_caption',
            field=models.TextField(verbose_name='Title Discription'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='main_title',
            field=models.CharField(max_length=300, verbose_name='Main Title'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 1, 48, 22, 676886), editable=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='review_star',
            field=models.IntegerField(blank=True, default=1, verbose_name='Star Rating(Max- 5)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='second_image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Second Image(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='second_title',
            field=models.TextField(verbose_name='Title 2'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='second_title_text_para1',
            field=models.TextField(verbose_name='Title 2 Paragraph 1'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='second_title_text_para2',
            field=models.TextField(verbose_name='Title 2 Paragraph 2'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Third Image(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title',
            field=models.TextField(verbose_name='Title 3'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_key_point1',
            field=models.TextField(blank=True, verbose_name='Key-Point1(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_key_point2',
            field=models.TextField(blank=True, verbose_name='Key-Point2(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_key_point3',
            field=models.TextField(blank=True, verbose_name='Key-Point3(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_key_point4',
            field=models.TextField(blank=True, verbose_name='Key-Point4(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_key_point5',
            field=models.TextField(blank=True, verbose_name='Key-Point5(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_para1',
            field=models.TextField(verbose_name='Title 3 Paragraph 1'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_para2',
            field=models.TextField(verbose_name='Title 3 Paragraph 2'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_para3',
            field=models.TextField(verbose_name='Title 3 Paragraph 3'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_para4',
            field=models.TextField(verbose_name='Title 3 Paragraph 4'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='url_str',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='video_clip',
            field=models.FileField(blank=True, editable=False, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='youtube_embed',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='youtube_video_status',
            field=models.BooleanField(default=False, verbose_name='Include Youtube Video'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='youtube_video_url',
            field=models.TextField(blank=True, verbose_name='Youtube Video Link(optional)'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 1, 48, 22, 674901)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 1, 48, 22, 678888)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 1, 48, 22, 679934)),
        ),
    ]
