# Generated by Django 3.0.6 on 2020-07-19 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200719_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='fourth_title',
            field=models.TextField(blank=True, editable=False, verbose_name='Title 4(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='fourth_title_text_para1',
            field=models.TextField(blank=True, editable=False, verbose_name='Title 4 Paragraph 1(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='fourth_title_text_para2',
            field=models.TextField(blank=True, editable=False, verbose_name='Title 4 Paragraph 2(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='fourth_title_text_para3',
            field=models.TextField(blank=True, editable=False, verbose_name='Title 4 Paragraph 3(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 8, 0, 18, 877476), editable=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='second_title',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='second_title_text_para1',
            field=models.TextField(blank=True, editable=False, verbose_name='Title 2 Paragraph 1'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='second_title_text_para2',
            field=models.TextField(blank=True, editable=False, verbose_name='Title 2 Paragraph 2'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title',
            field=models.TextField(blank=True, editable=False, verbose_name='Title 3'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_key_point1',
            field=models.TextField(blank=True, editable=False, verbose_name='Key-Point1(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_key_point2',
            field=models.TextField(blank=True, editable=False, verbose_name='Key-Point2(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_key_point3',
            field=models.TextField(blank=True, editable=False, verbose_name='Key-Point3(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_key_point4',
            field=models.TextField(blank=True, editable=False, verbose_name='Key-Point4(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_key_point5',
            field=models.TextField(blank=True, editable=False, verbose_name='Key-Point5(optional)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_para1',
            field=models.TextField(blank=True, editable=False, verbose_name='Title 3 Paragraph 1'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_para2',
            field=models.TextField(blank=True, editable=False, verbose_name='Title 3 Paragraph 2'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_para3',
            field=models.TextField(blank=True, editable=False, verbose_name='Title 3 Paragraph 3'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='third_title_text_para4',
            field=models.TextField(blank=True, editable=False, verbose_name='Title 3 Paragraph 4'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 8, 0, 18, 876652)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 8, 0, 18, 879157)),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 8, 0, 18, 880000)),
        ),
    ]
