# Generated by Django 3.0.6 on 2020-07-21 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200721_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='generate_contant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(editable=False, max_length=30)),
                ('youtube_link_togenerate', models.TextField()),
                ('generated_content', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 1, 51, 31, 495050), editable=False),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 1, 51, 31, 493938)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 1, 51, 31, 497387)),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 1, 51, 31, 498521)),
        ),
    ]
