# Generated by Django 3.0.6 on 2020-07-21 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200722_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_contant',
            name='translate',
            field=models.BooleanField(default=False, verbose_name='Translate to Hindi(if possible)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 4, 31, 23, 827596), editable=False),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 4, 31, 23, 826581)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 4, 31, 23, 829704)),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 4, 31, 23, 830779)),
        ),
    ]
