# Generated by Django 3.0.6 on 2020-07-22 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20200722_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 23, 31, 19, 739166), editable=False),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 23, 31, 19, 737999)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 23, 31, 19, 741950)),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 23, 31, 19, 743403)),
        ),
    ]
